# Generated by Django 3.0.2 on 2020-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_subservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='subservicio',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
