# Generated by Django 3.0.2 on 2020-01-31 18:10

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200131_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicio',
            name='image',
            field=models.ImageField(blank=True, storage=storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
