# Generated by Django 3.0.2 on 2020-02-01 01:04

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_subservicio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicio',
            name='image',
            field=models.ImageField(storage=storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
