# Generated by Django 3.0.2 on 2020-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sub_coah',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='sub_mex',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='sub_nl',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
