# Generated by Django 3.0.2 on 2020-02-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200203_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
