# Generated by Django 3.0.2 on 2020-02-19 21:45

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='image',
            field=models.ImageField(blank=True, storage=storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
