# Generated by Django 3.0.2 on 2020-02-01 00:44

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortadasYColumnas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=storage_backends.NewsMediaStorage(), upload_to='')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Portadas Y Columnas'), (2, 'Portadas Y Columnas de México')], default=1)),
            ],
        ),
    ]
