# Generated by Django 3.0.2 on 2020-02-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicos', '0003_portadasycolumnas_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portadasycolumnas',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
