# Generated by Django 3.0.2 on 2020-02-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicos', '0004_auto_20200131_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='portadasycolumnas',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
