# Generated by Django 3.0.2 on 2020-02-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicos', '0006_auto_20200131_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portadasycolumnas',
            name='date',
        ),
        migrations.AddField(
            model_name='portadasycolumnas',
            name='title',
            field=models.CharField(default=-1990, max_length=15),
            preserve_default=False,
        ),
    ]
