# Generated by Django 3.0.2 on 2020-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicos', '0007_auto_20200131_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portadasycolumnas',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Portadas Coahuila'), (2, 'Portadas México'), (3, 'Portadas Nuevo León')], default=1),
        ),
    ]
