# Generated by Django 3.0.2 on 2020-02-20 23:11

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('periodicos', '0008_auto_20200203_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(choices=[(1, 'Portadas Coahuila'), (2, 'Portadas México'), (3, 'Portadas Nuevo León')], default=1)),
                ('image', models.ImageField(blank=True, storage=storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
