# Generated by Django 3.0.2 on 2020-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Acerca de MAZ',
                'verbose_name_plural': 'Acerca de MAZ',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner configuration', 'verbose_name_plural': 'Banner configuration'},
        ),
    ]
