# Generated by Django 3.0.2 on 2020-02-03 21:43

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200203_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(storage=storage_backends.PublicMediaStorage(), upload_to='')),
            ],
            options={
                'verbose_name': 'Configuración de servicios',
                'verbose_name_plural': 'Configuración de servicios',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Configuración de banner', 'verbose_name_plural': 'Configuración de banner'},
        ),
    ]
