# Generated by Django 3.0.2 on 2020-02-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200203_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='header',
        ),
    ]
