# Generated by Django 3.0.2 on 2020-02-03 22:04

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_banner_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='banner',
            field=models.ImageField(blank=True, storage=storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
