# Generated by Django 3.0.2 on 2020-02-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_about_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
